const videoChallenges = [
  {
    id: "kafka-study-guide",
    area: "Kafka",
    title: "Guia visual profundo antes dos desafios Kafka",
    accent: "#0f766e",
    durationInFrames: 2100,
    fps: 15,
    scenario:
      "Antes de executar os labs, construa um mapa mental completo de como Kafka funciona por dentro.",
    steps: [
      "infra com brokers",
      "fluxo de pedidos",
      "log distribuido",
      "storage",
      "producer",
      "ISR",
      "replication",
      "consumer",
      "system design",
      "operacao",
    ],
    decisions: [
      "Relacionar cada lab a uma parte do pipeline Kafka.",
      "Separar plano de dados, plano de controle e estado operacional.",
      "Entrar nos desafios sabendo quais metricas e arquivos observar.",
    ],
    study: {
      kicker: "preparacao tecnica",
      headline:
        "Kafka de ponta a ponta: do pedido real ao broker, ISR, consumer e incidente",
      chapters: [
        {
          label: "Infra real",
          title: "Broker e um processo de servidor, normalmente em uma maquina propria",
          body:
            "Um broker Kafka e um processo JVM que roda em um servidor fisico, VM, container ou pod Kubernetes. Em producao, cada broker costuma ter disco, rede, CPU e IP/endereco proprio: por exemplo broker-1 10.0.10.11:9092, broker-2 10.0.10.12:9092 e broker-3 10.0.10.13:9092.",
          nodes: [
            ["client", "order-api\n10.0.20.50", "producer", 10, 42],
            ["b1", "broker-1\n10.0.10.11:9092", "broker", 38, 20],
            ["b2", "broker-2\n10.0.10.12:9092", "broker", 38, 48],
            ["b3", "broker-3\n10.0.10.13:9092", "broker", 38, 76],
            ["dns", "bootstrap\nkafka.prod:9092", "control", 66, 42],
            ["disk", "SSD/NVMe\nlog.dirs", "storage", 88, 42],
          ],
          flows: [
            ["client", "dns", "bootstrap"],
            ["dns", "b1", "metadata"],
            ["dns", "b2", "metadata"],
            ["dns", "b3", "metadata"],
            ["b1", "disk", "segments"],
            ["b2", "disk", "segments"],
          ],
          callouts: [
            "Broker nao e topic: broker e servidor/processo; topic e dado distribuido nos brokers.",
            "Pode rodar em VM, bare metal, container ou Kubernetes, mas disco e rede continuam sendo limites reais.",
            "listeners/advertised.listeners dizem aos clientes qual endereco usar para chegar ao broker.",
          ],
        },
        {
          label: "Pedido real",
          title: "Contexto: um pedido vira uma sequencia de eventos de dominio",
          body:
            "Imagine order_id=ORD-9001. O checkout confirma o pedido, pagamento aprova, estoque reserva e envio despacha. Kafka transporta esses fatos como eventos: OrderCreated, PaymentApproved, StockReserved e OrderShipped.",
          nodes: [
            ["checkout", "checkout-api\nOrderCreated", "producer", 10, 38],
            ["topic", "orders.events\nkey=ORD-9001", "topic", 34, 38],
            ["payment", "payment-service\nPaymentApproved", "producer", 58, 18],
            ["stock", "stock-service\nStockReserved", "producer", 58, 46],
            ["shipping", "shipping-service\nOrderShipped", "producer", 58, 74],
            ["projection", "order-view\nconsumer", "consumer", 88, 46],
          ],
          flows: [
            ["checkout", "topic", "event 1"],
            ["topic", "payment", "react"],
            ["payment", "topic", "event 2"],
            ["topic", "stock", "react"],
            ["stock", "topic", "event 3"],
            ["topic", "shipping", "event 4"],
            ["topic", "projection", "read model"],
          ],
          callouts: [
            "Kafka nao decide regra de negocio; ele preserva e distribui fatos para outros servicos.",
            "Usar key=order_id concentra os eventos do mesmo pedido na mesma partition.",
            "A ordem relevante aqui e por pedido, nao ordem global de todos os pedidos.",
          ],
        },
        {
          label: "Modelo mental",
          title: "Kafka e um log distribuido particionado",
          body:
            "Producer escreve records em topics; topics sao divididos em partitions; cada partition e um log ordenado por offset. Consumers leem sem apagar dados. Para ORD-9001, a partition funciona como uma trilha historica dos fatos desse pedido.",
          nodes: [
            ["producer", "Producer\napp", "producer", 12, 42],
            ["topic", "Topic\norders.events", "topic", 36, 42],
            ["p0", "Partition 0\noffset 0..N", "topic", 62, 24],
            ["p1", "Partition 1\noffset 0..N", "topic", 62, 58],
            ["consumer", "Consumer\ngroup", "consumer", 86, 42],
          ],
          flows: [
            ["producer", "topic", "send"],
            ["topic", "p0", "key route"],
            ["topic", "p1", "key route"],
            ["p0", "consumer", "fetch"],
            ["p1", "consumer", "fetch"],
          ],
          callouts: [
            "Consumir nao remove a mensagem; retention controla por quanto tempo ela fica.",
            "Offset e posicao dentro de uma partition, nao do topic inteiro.",
            "Ordenacao e local a uma partition; para ordem por pedido, use key=order_id.",
          ],
        },
        {
          label: "Ordem dos fatos",
          title: "System design: qual ordem realmente precisa ser preservada?",
          body:
            "Em system design, pergunte: preciso de ordem global ou ordem por entidade? Para pedidos, normalmente basta preservar a ordem dos eventos de um mesmo order_id. Isso evita serializar o sistema inteiro e permite paralelismo entre pedidos diferentes.",
          nodes: [
            ["o1a", "ORD-9001\nCreated", "producer", 12, 24],
            ["o1b", "ORD-9001\nPaid", "producer", 12, 48],
            ["o1c", "ORD-9001\nShipped", "producer", 12, 72],
            ["p7", "Partition 7\nkey=ORD-9001", "topic", 45, 48],
            ["o2", "ORD-9002\nparallel", "producer", 45, 18],
            ["p3", "Partition 3\nkey=ORD-9002", "topic", 76, 18],
            ["worker", "Consumers\nparallel", "consumer", 86, 56],
          ],
          flows: [
            ["o1a", "p7", "append 100"],
            ["o1b", "p7", "append 101"],
            ["o1c", "p7", "append 102"],
            ["o2", "p3", "append 40"],
            ["p7", "worker", "ordered by order"],
            ["p3", "worker", "parallel order"],
          ],
          callouts: [
            "Ordem global reduz throughput e raramente e requisito real.",
            "Ordem por entidade vem da key e da partition.",
            "Se dois producers publicam eventos do mesmo pedido, a aplicacao precisa controlar causalidade.",
          ],
        },
        {
          label: "Storage",
          title: "Records viram batches, segmentos e indices",
          body:
            "O broker anexa batches ao leader log. Segmentos .log, .index e .timeindex tornam retention, compaction e busca por offset viaveis.",
          nodes: [
            ["batch", "Record batch\ncompressed", "producer", 12, 38],
            ["leader", "Leader log\nappend-only", "broker", 36, 38],
            ["segment", "Segment\n000000.log", "storage", 60, 24],
            ["index", "Offset/time\nindexes", "storage", 60, 58],
            ["cache", "OS page cache\nfast fetch", "broker", 84, 42],
          ],
          flows: [
            ["batch", "leader", "append"],
            ["leader", "segment", "roll segment"],
            ["segment", "index", "sparse lookup"],
            ["segment", "cache", "cached read"],
            ["index", "cache", "seek"],
          ],
          callouts: [
            "Kafka evita update in-place no caminho quente.",
            "Segmentos sao a unidade pratica de limpeza e retencao.",
            "Batching melhora throughput e compressao; page cache evita ler tudo diretamente do disco.",
          ],
        },
        {
          label: "Producer",
          title: "Confiabilidade nasce de acks, retries e idempotencia",
          body:
            "O producer escolhe partition, envia batches e aguarda acknowledgments. Idempotencia usa producer id e sequence number para retry sem duplicar no log.",
          nodes: [
            ["app", "Producer\npid + seq", "producer", 12, 42],
            ["partitioner", "Partitioner\nkey hash", "control", 34, 42],
            ["leader", "Leader\nappend", "broker", 58, 42],
            ["isr", "ISR followers\nreplicate", "broker", 82, 26],
            ["ack", "ACK\nacks=all", "consumer", 82, 62],
          ],
          flows: [
            ["app", "partitioner", "serialize"],
            ["partitioner", "leader", "batch"],
            ["leader", "isr", "replicate"],
            ["isr", "ack", "min ISR"],
            ["ack", "app", "success/retry"],
          ],
          callouts: [
            "acks=all precisa de min.insync.replicas coerente.",
            "Retries sem idempotencia podem duplicar registros.",
            "max.in.flight afeta ordering em cenarios de retry; idempotencia usa sequence number por producer/partition.",
          ],
        },
        {
          label: "ISR no detalhe",
          title: "ISR e o conjunto de replicas que ainda acompanham o leader",
          body:
            "ISR significa In-Sync Replicas. Se RF=3, replicas podem estar em broker-1, broker-2 e broker-3. Uma replica fica no ISR enquanto busca dados do leader dentro do limite aceito. Se atrasa demais ou cai, sai do ISR; acks=all espera confirmacao das replicas ainda no ISR.",
          nodes: [
            ["leader", "Leader P0\nbroker-1", "broker", 18, 42],
            ["r2", "Replica P0\nbroker-2 in ISR", "broker", 50, 22],
            ["r3", "Replica P0\nbroker-3 in ISR", "broker", 50, 62],
            ["slow", "broker-3 lento\npode sair ISR", "control", 80, 62],
            ["producer", "Producer\nacks=all", "producer", 18, 76],
            ["minisr", "min.insync\nreplicas=2", "control", 80, 22],
          ],
          flows: [
            ["producer", "leader", "append"],
            ["leader", "r2", "fetch/replicate"],
            ["leader", "r3", "fetch/replicate"],
            ["r3", "slow", "lag timeout"],
            ["r2", "minisr", "ack counted"],
            ["r3", "minisr", "ack if in ISR"],
          ],
          callouts: [
            "RF e numero de copias; ISR e subconjunto atualmente sincronizado.",
            "min.insync.replicas define quantas replicas precisam estar sincronas para aceitar write seguro com acks=all.",
            "Se ISR cai abaixo do minimo, o producer recebe erro em vez de fingir durabilidade.",
          ],
        },
        {
          label: "Replication",
          title: "Leader, followers, ISR e high watermark",
          body:
            "Cada partition tem um leader. Followers replicam buscando dados do leader. O high watermark e o maior offset que ja foi replicado conforme a regra de seguranca; consumers so devem ver registros ate esse ponto.",
          nodes: [
            ["producer", "Producer\nacks=all", "producer", 10, 42],
            ["leader", "Leader\nP0", "broker", 35, 32],
            ["f1", "Follower\nin ISR", "broker", 62, 20],
            ["f2", "Follower\nlagging?", "broker", 62, 58],
            ["hw", "High watermark\nvisible", "control", 35, 72],
            ["consumer", "Consumer\nread safe", "consumer", 86, 42],
          ],
          flows: [
            ["producer", "leader", "append"],
            ["leader", "f1", "replicate"],
            ["leader", "f2", "replicate"],
            ["f1", "hw", "confirmed"],
            ["hw", "consumer", "fetch <= HW"],
          ],
          callouts: [
            "ISR muda com saude e atraso das replicas; nao e lista estatica.",
            "High watermark protege contra leitura de dados que poderiam sumir apos falha.",
            "Leader election e por partition; broker-2 pode liderar P0 enquanto broker-1 lidera P1.",
          ],
        },
        {
          label: "KRaft",
          title: "Metadata tambem e log replicado",
          body:
            "Em KRaft, controllers mantem um quorum e replicam o metadata log. Brokers acompanham essa imagem para saber topics, partitions, leaders e configs.",
          nodes: [
            ["admin", "Admin client\ncreate topic", "producer", 10, 42],
            ["c1", "Controller\nleader", "control", 36, 28],
            ["c2", "Controller\nvoter", "control", 62, 20],
            ["c3", "Controller\nvoter", "control", 62, 58],
            ["meta", "Metadata log\nquorum", "storage", 36, 72],
            ["broker", "Broker\nmetadata image", "broker", 86, 42],
          ],
          flows: [
            ["admin", "c1", "mutation"],
            ["c1", "c2", "Raft"],
            ["c1", "c3", "Raft"],
            ["c1", "meta", "commit"],
            ["meta", "broker", "snapshot/update"],
          ],
          callouts: [
            "KRaft remove ZooKeeper, mas depende de quorum saudavel.",
            "Plano de controle diferente de plano de dados.",
            "Metadata degradada afeta criacao, alteracao e eleicao.",
          ],
        },
        {
          label: "Consumers",
          title: "Consumer group divide partitions e grava progresso",
          body:
            "O coordinator gerencia membership, assignments e offsets. Rebalance redistribui partitions; commit de offset grava progresso do grupo.",
          nodes: [
            ["topic", "Topic\nP0 P1 P2", "topic", 10, 42],
            ["coord", "Group coordinator\nassignment", "control", 38, 42],
            ["c1", "Consumer A\nP0 P1", "consumer", 68, 26],
            ["c2", "Consumer B\nP2", "consumer", 68, 58],
            ["offsets", "__consumer_offsets\ncommits", "storage", 88, 42],
          ],
          flows: [
            ["c1", "coord", "heartbeat"],
            ["c2", "coord", "heartbeat"],
            ["coord", "topic", "assign"],
            ["topic", "c1", "fetch"],
            ["c1", "offsets", "commit"],
            ["c2", "offsets", "commit"],
          ],
          callouts: [
            "Um grupo processa uma partition por consumer ativo.",
            "Rebalance pode pausar consumo, dependendo do protocolo.",
            "Commit depois do efeito favorece at-least-once; commit antes pode perder trabalho se o worker cair.",
          ],
        },
        {
          label: "Keys",
          title: "Partition key e o limite real da ordenacao",
          body:
            "A key define rota para partition. Isso preserva ordem por entidade, mas uma key concentrada cria hot partition e limita paralelismo.",
          nodes: [
            ["events", "Events\norder/customer", "producer", 10, 42],
            ["hash", "Hash(key)\npartitioner", "control", 34, 42],
            ["p0", "P0\nordered lane", "topic", 60, 22],
            ["p1", "P1\nparallel lane", "topic", 60, 48],
            ["hot", "P2\nhot key", "topic", 60, 74],
            ["workers", "Consumers\nparallel", "consumer", 86, 48],
          ],
          flows: [
            ["events", "hash", "key"],
            ["hash", "p0", "route"],
            ["hash", "p1", "route"],
            ["hash", "hot", "skew"],
            ["p0", "workers", "ordered"],
            ["p1", "workers", "parallel"],
          ],
          callouts: [
            "Ordem global custa caro; Kafka oferece ordem por partition.",
            "Key deve refletir a entidade que exige causalidade.",
            "Skew aparece em lag/bytes/records por partition.",
          ],
        },
        {
          label: "Retention",
          title: "Retention delete e compaction respondem perguntas diferentes",
          body:
            "Retention por tempo/tamanho controla historico. Log compaction preserva o ultimo valor por key e tombstones removem estado.",
          nodes: [
            ["producer", "Updates\nA1 A2 B1", "producer", 10, 42],
            ["log", "Log segments\nhistory", "topic", 36, 42],
            ["delete", "Delete retention\nwindow", "control", 62, 24],
            ["compact", "Compaction\nlatest per key", "control", 62, 60],
            ["state", "Replay\nstate restore", "consumer", 86, 42],
          ],
          flows: [
            ["producer", "log", "append"],
            ["log", "delete", "expire segments"],
            ["log", "compact", "clean old keys"],
            ["compact", "state", "snapshot-ish log"],
            ["delete", "state", "replay window"],
          ],
          callouts: [
            "Delete retention guarda historico por janela.",
            "Compaction serve reconstruir estado por key.",
            "Tombstone depende de delete retention para sumir.",
          ],
        },
        {
          label: "Contratos",
          title: "Schemas e evolucao protegem consumidores independentes",
          body:
            "Eventos sao contratos entre times. Evolucao segura exige compatibilidade, campos opcionais, semantica clara e estrategia de depreciacao.",
          nodes: [
            ["p1", "Producer v1\nschema A", "producer", 10, 28],
            ["p2", "Producer v2\nschema A+", "producer", 10, 58],
            ["registry", "Schema registry\ncompatibility", "control", 38, 42],
            ["topic", "Topic\nschema id", "topic", 64, 42],
            ["old", "Consumer old\ncompatible", "consumer", 88, 26],
            ["new", "Consumer new\nuses field", "consumer", 88, 60],
          ],
          flows: [
            ["p1", "registry", "register"],
            ["p2", "registry", "validate"],
            ["registry", "topic", "schema id"],
            ["topic", "old", "backward"],
            ["topic", "new", "forward"],
          ],
          callouts: [
            "Compatibilidade e decisao de produto e operacao.",
            "Campo obrigatorio novo quebra consumidores antigos.",
            "Contrato precisa documentar significado, nao so formato.",
          ],
        },
        {
          label: "Garantias",
          title: "Transactions/EOS fecham um ciclo Kafka-para-Kafka",
          body:
            "Transacoes coordenam writes e offsets no Kafka. read_committed esconde dados abortados, mas efeitos externos seguem fora dessa garantia.",
          nodes: [
            ["input", "Input topic\norders", "topic", 10, 42],
            ["app", "Processor\ntransactional.id", "consumer", 36, 42],
            ["txn", "Transaction\ncoordinator", "control", 62, 24],
            ["output", "Output topic\nresults", "topic", 86, 42],
            ["offsets", "Offsets\nin txn", "storage", 62, 64],
          ],
          flows: [
            ["input", "app", "consume"],
            ["app", "txn", "begin"],
            ["app", "output", "produce"],
            ["app", "offsets", "sendOffsets"],
            ["txn", "output", "commit marker"],
            ["txn", "offsets", "atomic commit"],
          ],
          callouts: [
            "EOS nao torna APIs externas exatamente-once.",
            "transactional.id tambem permite fencing.",
            "Consumers read_committed veem apenas commits.",
          ],
        },
        {
          label: "Falhas",
          title: "System design: tolerancia a falha e ordem do incidente",
          body:
            "Quando broker-1 cai, partitions que ele liderava precisam de novo leader entre replicas elegiveis. O sistema continua se houver quorum/ISR suficiente. A ordem do incidente importa: detectar falha, eleger leader, producers atualizam metadata, consumers retomam fetch.",
          nodes: [
            ["b1", "broker-1\nleader caiu", "broker", 12, 42],
            ["ctrl", "controller\nleader election", "control", 38, 42],
            ["b2", "broker-2\nnew leader", "broker", 64, 24],
            ["b3", "broker-3\nfollower", "broker", 64, 62],
            ["clients", "clients\nrefresh metadata", "producer", 88, 42],
            ["slo", "SLO\nlatency/availability", "storage", 38, 72],
          ],
          flows: [
            ["b1", "ctrl", "failure detected"],
            ["ctrl", "b2", "elect leader"],
            ["b2", "b3", "replicate"],
            ["ctrl", "clients", "metadata update"],
            ["clients", "b2", "resume writes"],
            ["ctrl", "slo", "measure impact"],
          ],
          callouts: [
            "Tolerancia a falha e trade-off entre RF, min ISR, latencia e custo.",
            "Nao basta subir 3 brokers: partitions, leaders e rack awareness precisam estar bem distribuidos.",
            "O desenho de system design deve dizer o que acontece antes, durante e depois da falha.",
          ],
        },
        {
          label: "Operacao",
          title: "Performance, seguranca e observabilidade fecham o sistema",
          body:
            "Kafka em producao exige throughput medido, quotas, ACLs, lag por partition, ISR, disco, capacidade e runbooks de incidente.",
          nodes: [
            ["clients", "Clients\nTLS/SASL", "producer", 10, 42],
            ["broker", "Broker\nquotas/ACLs", "broker", 34, 42],
            ["metrics", "Metrics\nlag ISR disk", "storage", 58, 24],
            ["alerts", "Alerts\nSLO", "control", 58, 60],
            ["runbook", "Runbook\nmitigate", "external", 84, 42],
          ],
          flows: [
            ["clients", "broker", "auth + traffic"],
            ["broker", "metrics", "emit"],
            ["metrics", "alerts", "threshold"],
            ["alerts", "runbook", "diagnose"],
            ["runbook", "broker", "scale/tune"],
          ],
          callouts: [
            "Lag sem contexto nao diz se o problema e broker, consumer ou key skew.",
            "Quotas evitam que um tenant degrade todos.",
            "Runbook liga metrica a decisao e rollback.",
          ],
        },
      ],
    },
  },
  {
    id: "kafka-single-broker",
    area: "Kafka",
    title: "Producer, consumer e offsets",
    accent: "#0f766e",
    scenario: "Um worker precisa consumir eventos de pedidos sem perder mensagens quando falha.",
    steps: ["subir broker", "publicar evento", "consumir", "commitar offset", "reprocessar"],
    decisions: ["key=order_id", "commit depois do efeito", "consumer idempotente"],
  },
  {
    id: "kafka-record-lifecycle",
    area: "Kafka",
    title: "Ciclo de vida do record",
    accent: "#0f766e",
    scenario: "Um record percorre producer, broker, segmentos de log, indices e page cache.",
    steps: ["criar topic", "produzir batch", "inspecionar .log", "ver .index", "ligar a page cache"],
    decisions: ["batching", "segmentacao", "retention por segmento"],
  },
  {
    id: "kafka-producer-reliability",
    area: "Kafka",
    title: "Producer confiavel",
    accent: "#0f766e",
    scenario: "Eventos financeiros precisam sobreviver a retry, falha de broker e leader election.",
    steps: ["acks=all", "RF=3", "min ISR", "idempotencia", "falha de broker"],
    decisions: ["durabilidade", "latencia", "ordenacao em retry"],
  },
  {
    id: "kafka-consumer-offsets",
    area: "Kafka",
    title: "Consumer offsets e lag",
    accent: "#0f766e",
    scenario: "Um consumer atrasou e o time precisa medir lag, resetar offset e reprocessar com seguranca.",
    steps: ["produzir lote", "criar group", "medir lag", "resetar offset", "replay seguro"],
    decisions: ["commit manual", "idempotencia", "reset controlado"],
  },
  {
    id: "kafka-internals-cluster",
    area: "Kafka",
    title: "Replication, ISR e leader election",
    accent: "#0f766e",
    scenario: "Um topic critico precisa sobreviver a queda de broker com durabilidade clara.",
    steps: ["subir 3 brokers", "criar topic RF=3", "observar ISR", "derrubar broker", "avaliar leader"],
    decisions: ["replication factor", "min.insync.replicas", "acks=all"],
  },
  {
    id: "kafka-kraft-metadata",
    area: "Kafka",
    title: "KRaft e metadata quorum",
    accent: "#0f766e",
    scenario: "Um cluster moderno precisa coordenar metadata sem ZooKeeper.",
    steps: ["controller quorum", "metadata log", "brokers", "falha de controller", "topologia"],
    decisions: ["KRaft", "quorum", "plano de controle"],
  },
  {
    id: "kafka-rebalance-protocols",
    area: "Kafka",
    title: "Rebalance protocols",
    accent: "#0f766e",
    scenario: "Deploys frequentes causam rebalances, pausas e picos de lag.",
    steps: ["join group", "assignment", "eager", "cooperative", "static membership"],
    decisions: ["assignor", "group.instance.id", "timeouts"],
  },
  {
    id: "kafka-partition-key-ordering",
    area: "Kafka",
    title: "Partition key e ordenacao",
    accent: "#0f766e",
    scenario: "Eventos do mesmo pedido precisam manter ordem sem sacrificar paralelismo global.",
    steps: ["criar topic", "usar order_id", "testar customer_id", "comparar skew", "medir lag"],
    decisions: ["order_id como key", "evitar hot partition", "ordem por partition"],
  },
  {
    id: "kafka-topic-design",
    area: "Kafka",
    title: "Topic design",
    accent: "#0f766e",
    scenario: "Um catalogo de topics precisa de naming, owner, retention, RF e SLO claros.",
    steps: ["nomear topic", "definir owner", "partitions", "retention", "SLO"],
    decisions: ["RF=3", "retention por replay", "ownership"],
  },
  {
    id: "kafka-retention-compaction",
    area: "Kafka",
    title: "Retention e compaction",
    accent: "#0f766e",
    scenario: "Um time quer reconstruir estado de cliente a partir de eventos Kafka.",
    steps: ["delete policy", "compact policy", "tombstone", "replay", "estado"],
    decisions: ["historico vs snapshot", "key estavel", "tombstone"],
  },
  {
    id: "kafka-schema-evolution",
    area: "Kafka",
    title: "Schema evolution",
    accent: "#0f766e",
    scenario: "OrderCreated precisa evoluir sem quebrar consumers antigos.",
    steps: ["schema v1", "campo opcional", "compatibilidade", "deprecacao", "validacao"],
    decisions: ["backward", "forward", "contrato de evento"],
  },
  {
    id: "kafka-transactions-eos",
    area: "Kafka",
    title: "Transactions e EOS",
    accent: "#0f766e",
    scenario: "Um fluxo Kafka para Kafka precisa publicar resultados e offsets atomicamente.",
    steps: ["transactional.id", "begin", "produce", "send offsets", "commit"],
    decisions: ["read_committed", "fencing", "limites externos"],
  },
  {
    id: "kafka-dlq-idempotency",
    area: "Kafka",
    title: "DLQ, poison message e idempotencia",
    accent: "#0f766e",
    scenario: "Mensagens invalidas nao podem travar pagamentos nem duplicar cobrancas.",
    steps: ["criar topics", "classificar erros", "retry", "DLQ", "replay controlado"],
    decisions: ["event_id idempotente", "payment_id externo", "DLQ nao e lixo"],
  },
  {
    id: "kafka-outbox-cdc",
    area: "Kafka",
    title: "Outbox e CDC",
    accent: "#0f766e",
    scenario: "Pedido gravado no banco precisa gerar evento Kafka sem dual write fragil.",
    steps: ["transacao local", "outbox", "CDC", "publicar", "deduplicar"],
    decisions: ["event_id", "relay vs CDC", "limpeza da outbox"],
  },
  {
    id: "kafka-stream-processing",
    area: "Kafka",
    title: "Stream processing",
    accent: "#0f766e",
    scenario: "Eventos de pedidos e pagamentos viram metricas por cliente em tempo quase real.",
    steps: ["KStream", "KTable", "state store", "changelog", "restore"],
    decisions: ["janela", "key", "stateful processing"],
  },
  {
    id: "kafka-performance-tuning",
    area: "Kafka",
    title: "Performance tuning",
    accent: "#0f766e",
    scenario: "Um pipeline precisa multiplicar throughput sem violar latencia p95.",
    steps: ["baseline", "batch", "linger", "compressao", "fetch"],
    decisions: ["throughput vs latencia", "CPU", "partitions"],
  },
  {
    id: "kafka-security-quotas",
    area: "Kafka",
    title: "Security e quotas",
    accent: "#0f766e",
    scenario: "Varios times compartilham o cluster e precisam de isolamento seguro.",
    steps: ["TLS", "SASL", "ACL", "principal", "quota"],
    decisions: ["least privilege", "multi-tenancy", "throttling"],
  },
  {
    id: "kafka-observability-incidents",
    area: "Kafka",
    title: "Observability e incidentes",
    accent: "#0f766e",
    scenario: "Lag subiu, ISR degradou e o time precisa diagnosticar sem improviso.",
    steps: ["lag", "ISR", "disco", "runbook", "pos-mortem"],
    decisions: ["alertas", "capacidade", "DR"],
  },
  {
    id: "dynamodb-single-table-orders",
    area: "DynamoDB",
    title: "Single-table design para pedidos",
    accent: "#2563eb",
    scenario: "Pedidos precisam ser consultados por order_id e por customer_id com baixa latencia.",
    steps: ["listar access patterns", "definir PK/SK", "criar GSI", "modelar itens", "validar consultas"],
    decisions: ["PK=ORDER#id", "GSI por cliente", "schema guiado por leitura"],
  },
  {
    id: "dynamodb-optimistic-locking",
    area: "DynamoDB",
    title: "Optimistic locking",
    accent: "#2563eb",
    scenario: "Dois workers competem pelo ultimo item em estoque e apenas um pode vencer.",
    steps: ["modelar estoque", "usar version", "ConditionExpression", "retry seguro", "comparar transacao"],
    decisions: ["sem lock externo", "reservation_id", "TransactWrite quando necessario"],
  },
  {
    id: "sqs-standard-worker",
    area: "SQS",
    title: "Standard queue com DLQ",
    accent: "#b45309",
    scenario: "Jobs de nota fiscal podem falhar, duplicar e precisam de redrive previsivel.",
    steps: ["criar DLQ", "criar fila", "visibility timeout", "long polling", "idempotencia"],
    decisions: ["Standard sem ordem", "timeout=2x p99", "maxReceiveCount=5"],
  },
  {
    id: "sqs-fifo-ordering",
    area: "SQS",
    title: "FIFO, ordem e deduplicacao",
    accent: "#b45309",
    scenario: "Status de um pedido precisa manter ordem, mas pedidos diferentes podem paralelizar.",
    steps: ["criar FIFO", "MessageGroupId", "DeduplicationId", "testar bloqueio", "comparar Kafka"],
    decisions: ["group=order_id", "dedup=event_id", "cuidado com head-of-line"],
  },
  {
    id: "system-design-rate-limiter",
    area: "System Design",
    title: "Rate limiter: Token Bucket",
    accent: "#7c3aed",
    scenario: "Uma API publica precisa controlar abuso com bursts permitidos por plano.",
    steps: ["definir limites", "comparar algoritmos", "Redis Lua", "headers 429", "fallback"],
    decisions: ["Token Bucket", "chave por tenant", "fail-open ou fail-closed"],
  },
  {
    id: "system-design-marketplace",
    area: "System Design",
    title: "Marketplace orientado a eventos",
    accent: "#7c3aed",
    scenario: "Checkout responde rapido enquanto pagamento, estoque e notificacao seguem assincronos.",
    steps: ["NFRs", "monolito modular", "outbox", "eventos", "falhas parciais"],
    decisions: ["Saga", "Kafka vs SQS", "consistencia eventual"],
  },
  {
    id: "system-design-notifications",
    area: "System Design",
    title: "Notificacoes multicanal",
    accent: "#7c3aed",
    scenario: "Email, SMS, push e WhatsApp precisam respeitar limites e evitar duplicidade.",
    steps: ["canais", "eventos", "retry", "DLQ", "bulkheads"],
    decisions: ["backoff com jitter", "idempotency key", "fila/topic por canal"],
  },
];

const kafkaVisuals = {
  "kafka-single-broker": {
    headline: "Fluxo mínimo: produzir, persistir, consumir e avançar offset",
    detail:
      "O vídeo mostra que o consumer não lê de uma fila invisível: ele busca records em uma partition, processa e só então grava o offset do grupo em __consumer_offsets.",
    nodes: [
      ["producer", "Producer\norder-api", "producer", 12, 34],
      ["broker", "Broker 1\nappend log", "broker", 39, 34],
      ["topic", "orders.v1\npartition 0", "topic", 62, 34],
      ["consumer", "Consumer\nworker", "consumer", 84, 34],
      ["offsets", "__consumer_offsets\ngroup state", "storage", 62, 72],
    ],
    flows: [
      ["producer", "broker", "send(record)"],
      ["broker", "topic", "append offset N"],
      ["topic", "consumer", "fetch batch"],
      ["consumer", "offsets", "commit offset N+1"],
    ],
    callouts: [
      "Offset identifica posição dentro da partition, não confirmação global do topic.",
      "Commit depois do efeito reduz perda, mas exige idempotência contra reprocessamento.",
      "Key estável mantém eventos relacionados na mesma partition.",
    ],
  },
  "kafka-record-lifecycle": {
    headline: "Do batch do producer ao segmento no disco",
    detail:
      "O record entra em lote, é anexado ao log imutável, ganha índices para busca por offset/tempo e normalmente é servido via page cache do sistema operacional.",
    nodes: [
      ["batch", "Producer batch\ncompression", "producer", 12, 28],
      ["leader", "Leader replica\nappend-only", "broker", 36, 28],
      ["segment", "000000.log\nsegment", "storage", 60, 28],
      ["index", ".index + .timeindex\nlookup", "storage", 60, 66],
      ["pagecache", "OS page cache\nzero-copy path", "broker", 84, 46],
    ],
    flows: [
      ["batch", "leader", "network request"],
      ["leader", "segment", "append bytes"],
      ["segment", "index", "offset index"],
      ["segment", "pagecache", "cached reads"],
      ["index", "pagecache", "seek + fetch"],
    ],
    callouts: [
      "Kafka é rápido porque escreve sequencialmente e evita mutações por record.",
      "Retention opera por segmentos, então tamanho e tempo de segmentação importam.",
      "Índices aceleram seek sem transformar Kafka em banco relacional.",
    ],
  },
  "kafka-producer-reliability": {
    headline: "Durabilidade depende de acks, ISR e idempotência",
    detail:
      "A animação compara o caminho do record até o leader, a replicação para followers em ISR e o ACK só depois que a política de durabilidade é satisfeita.",
    nodes: [
      ["producer", "Idempotent\nproducer", "producer", 11, 42],
      ["leader", "Leader\nbroker 1", "broker", 38, 28],
      ["f2", "Follower\nbroker 2", "broker", 64, 20],
      ["f3", "Follower\nbroker 3", "broker", 64, 55],
      ["ack", "ACK\nacks=all", "consumer", 38, 72],
    ],
    flows: [
      ["producer", "leader", "pid + sequence"],
      ["leader", "f2", "replicate"],
      ["leader", "f3", "replicate"],
      ["f2", "ack", "in ISR"],
      ["f3", "ack", "min ISR met"],
      ["ack", "producer", "safe ack"],
    ],
    callouts: [
      "acks=all só é forte quando min.insync.replicas está configurado corretamente.",
      "Idempotência remove duplicatas de retry dentro da sessão do producer.",
      "max.in.flight alto pode afetar ordenação quando há retry em cenários legados.",
    ],
  },
  "kafka-consumer-offsets": {
    headline: "Lag é distância entre posição produzida e posição confirmada",
    detail:
      "O consumer busca lotes, processa efeitos externos e move o committed offset. Reset e replay mudam a posição do grupo, não apagam dados do topic.",
    nodes: [
      ["log", "Topic partition\nLEO=140", "topic", 16, 35],
      ["consumer", "Consumer group\nposition=118", "consumer", 45, 35],
      ["sideeffect", "DB/API effect\nidempotent", "external", 73, 22],
      ["offsets", "__consumer_offsets\ncommitted=110", "storage", 73, 58],
      ["reset", "offset reset\nreplay window", "control", 45, 74],
    ],
    flows: [
      ["log", "consumer", "fetch 111..118"],
      ["consumer", "sideeffect", "process"],
      ["consumer", "offsets", "manual commit"],
      ["reset", "consumer", "seek/reset"],
      ["offsets", "reset", "current checkpoint"],
    ],
    callouts: [
      "Commit automático pode confirmar antes do efeito de negócio terminar.",
      "Lag precisa ser lido por partition e por grupo, não como média solta.",
      "Replay seguro exige deduplicação e janela explícita de reprocessamento.",
    ],
  },
  "kafka-internals-cluster": {
    headline: "Leader, followers, ISR e high watermark",
    detail:
      "O vídeo mostra que consumers só enxergam records abaixo do high watermark, ou seja, replicados de acordo com o conjunto ISR atual.",
    nodes: [
      ["producer", "Producer\nacks=all", "producer", 10, 40],
      ["leader", "Leader P0\nbroker 1", "broker", 35, 32],
      ["follower2", "Follower P0\nbroker 2", "broker", 61, 22],
      ["follower3", "Follower P0\nbroker 3", "broker", 61, 56],
      ["consumer", "Consumer\nreads <= HW", "consumer", 86, 40],
      ["hw", "High watermark\nsafe offset", "control", 35, 72],
    ],
    flows: [
      ["producer", "leader", "append"],
      ["leader", "follower2", "replicate"],
      ["leader", "follower3", "replicate"],
      ["follower2", "hw", "ISR ack"],
      ["hw", "consumer", "visible records"],
      ["follower3", "consumer", "leader election candidate"],
    ],
    callouts: [
      "ISR não é lista fixa; followers lentos podem sair do conjunto.",
      "High watermark evita leitura de records que ainda podem desaparecer.",
      "Leader election precisa preservar durabilidade e disponibilidade sob falha.",
    ],
  },
  "kafka-kraft-metadata": {
    headline: "KRaft separa plano de controle via metadata log",
    detail:
      "Sem ZooKeeper, controllers formam um quorum Raft que replica alterações de metadata; brokers consomem esse log para saber topics, leaders e configs.",
    nodes: [
      ["admin", "Admin client\ncreate topic", "producer", 11, 43],
      ["controller1", "Controller quorum\nleader", "control", 36, 28],
      ["controller2", "Controller\nvoter", "control", 60, 20],
      ["controller3", "Controller\nvoter", "control", 60, 56],
      ["metalog", "__cluster_metadata\nlog", "storage", 36, 72],
      ["broker", "Broker\nmetadata cache", "broker", 84, 43],
    ],
    flows: [
      ["admin", "controller1", "metadata mutation"],
      ["controller1", "controller2", "Raft replicate"],
      ["controller1", "controller3", "Raft replicate"],
      ["controller1", "metalog", "commit metadata"],
      ["metalog", "broker", "metadata image"],
    ],
    callouts: [
      "KRaft remove ZooKeeper, mas não remove a necessidade de quorum saudável.",
      "Metadata também é log replicado, com liderança e commit.",
      "Plano de controle degradado afeta criação de topics e eleição de leaders.",
    ],
  },
  "kafka-rebalance-protocols": {
    headline: "Rebalance decide quem possui cada partition",
    detail:
      "A cena compara o group coordinator distribuindo assignments e mostra por que cooperative/static membership reduzem pausas durante deploys.",
    nodes: [
      ["topic", "Topic\nP0 P1 P2 P3", "topic", 12, 42],
      ["coordinator", "Group coordinator\nassignment", "control", 40, 42],
      ["c1", "Consumer A\nmember", "consumer", 70, 22],
      ["c2", "Consumer B\nmember", "consumer", 70, 48],
      ["c3", "Consumer C\nnew member", "consumer", 70, 74],
      ["offsets", "__consumer_offsets\ngroup metadata", "storage", 40, 76],
    ],
    flows: [
      ["c1", "coordinator", "heartbeat"],
      ["c2", "coordinator", "heartbeat"],
      ["c3", "coordinator", "join group"],
      ["coordinator", "topic", "revoke/assign partitions"],
      ["coordinator", "offsets", "persist generation"],
    ],
    callouts: [
      "Eager rebalance pausa tudo; cooperative revoga em etapas.",
      "Static membership reduz rebalance quando um pod reinicia rápido.",
      "KIP-848 move mais lógica de coordenação para o broker.",
    ],
  },
  "kafka-partition-key-ordering": {
    headline: "A key escolhe a partition e define o escopo de ordenação",
    detail:
      "Eventos com a mesma key seguem para a mesma partition. Isso preserva ordem local, mas keys muito populares criam hot partitions.",
    nodes: [
      ["events", "Events\norder_id/customer_id", "producer", 10, 42],
      ["partitioner", "Partitioner\nhash(key)", "control", 34, 42],
      ["p0", "P0\norder-17", "topic", 62, 20],
      ["p1", "P1\norder-18", "topic", 62, 44],
      ["p2", "P2\nhot key?", "topic", 62, 68],
      ["workers", "Consumers\nparallelism", "consumer", 86, 44],
    ],
    flows: [
      ["events", "partitioner", "serialize + key"],
      ["partitioner", "p0", "hash route"],
      ["partitioner", "p1", "hash route"],
      ["partitioner", "p2", "skew risk"],
      ["p0", "workers", "ordered stream"],
      ["p1", "workers", "parallel stream"],
    ],
    callouts: [
      "Kafka só garante ordem dentro de uma partition.",
      "Mais partitions aumentam paralelismo, mas também custo operacional.",
      "A key precisa refletir a entidade que exige causalidade.",
    ],
  },
  "kafka-topic-design": {
    headline: "Topic design torna ownership e SLO explícitos",
    detail:
      "O desenho liga contrato, retenção, replication factor, partitions e consumidores para mostrar que topic não é só nome: é uma API operacional.",
    nodes: [
      ["owner", "Owner + SLA\nteam pedidos", "external", 10, 36],
      ["contract", "Event contract\nOrderCreated", "control", 34, 22],
      ["topic", "orders.events.v1\nRF/partitions", "topic", 58, 36],
      ["retention", "Retention\nreplay window", "storage", 34, 62],
      ["consumers", "Consumers\nanalytics/fraud", "consumer", 84, 36],
      ["catalog", "Catalog\nmetadata", "storage", 58, 72],
    ],
    flows: [
      ["owner", "contract", "schema + semantics"],
      ["contract", "topic", "publish API"],
      ["retention", "topic", "storage policy"],
      ["topic", "consumers", "subscription"],
      ["topic", "catalog", "discoverability"],
    ],
    callouts: [
      "Nome, owner e semântica evitam topics órfãos e eventos ambíguos.",
      "Partition count é decisão difícil de reduzir depois.",
      "Retention deve nascer do requisito de replay, auditoria e custo.",
    ],
  },
  "kafka-retention-compaction": {
    headline: "Delete retention guarda histórico; compaction guarda último estado por key",
    detail:
      "A animação mostra records repetidos por key, tombstone e limpeza assíncrona preservando a versão mais recente necessária para reconstruir estado.",
    nodes: [
      ["producer", "Producer\ncustomer updates", "producer", 10, 42],
      ["log", "Log\nA1 A2 B1 tombstone", "topic", 36, 42],
      ["cleaner", "Log cleaner\ncompaction", "control", 62, 26],
      ["snapshot", "Compacted log\nlatest per key", "storage", 84, 42],
      ["replay", "Replay\nmaterialized state", "consumer", 62, 70],
    ],
    flows: [
      ["producer", "log", "append history"],
      ["log", "cleaner", "scan segments"],
      ["cleaner", "snapshot", "keep latest"],
      ["snapshot", "replay", "restore state"],
      ["log", "replay", "delete retention window"],
    ],
    callouts: [
      "Compaction não é imediata; consumers ainda podem ver registros antigos.",
      "Tombstones removem keys, mas dependem de retenção de deletes.",
      "Use key estável quando o topic representa estado por entidade.",
    ],
  },
  "kafka-schema-evolution": {
    headline: "Contrato de evento precisa evoluir sem quebrar consumidores",
    detail:
      "O fluxo passa por producer, registry/contrato, topic e consumers em versões diferentes para visualizar compatibilidade backward/forward.",
    nodes: [
      ["producer", "Producer v2\nnew optional field", "producer", 10, 42],
      ["registry", "Schema registry\ncompatibility", "control", 34, 42],
      ["topic", "orders.v1\nschema id", "topic", 58, 42],
      ["old", "Consumer v1\nignores field", "consumer", 84, 24],
      ["new", "Consumer v2\nuses field", "consumer", 84, 60],
      ["adr", "ADR\nmigration rule", "storage", 58, 72],
    ],
    flows: [
      ["producer", "registry", "validate schema"],
      ["registry", "topic", "schema id"],
      ["topic", "old", "backward path"],
      ["topic", "new", "new behavior"],
      ["registry", "adr", "compatibility policy"],
    ],
    callouts: [
      "Campo obrigatório novo tende a quebrar consumidores antigos.",
      "Compatibilidade é política de produto, não detalhe de serialização.",
      "Versione semântica do evento, não apenas estrutura JSON.",
    ],
  },
  "kafka-transactions-eos": {
    headline: "EOS coordena writes e offsets em uma transação Kafka",
    detail:
      "A cena mostra consume-process-produce com transactional.id, marker de commit/abort e consumer read_committed evitando resultados abortados.",
    nodes: [
      ["input", "Input topic\norders", "topic", 10, 42],
      ["processor", "Transactional\nprocessor", "consumer", 36, 42],
      ["txn", "Transaction\ncoordinator", "control", 60, 22],
      ["output", "Output topic\npayments", "topic", 84, 42],
      ["offsets", "Offsets in txn\nsendOffsets", "storage", 60, 66],
    ],
    flows: [
      ["input", "processor", "fetch"],
      ["processor", "txn", "begin txn"],
      ["processor", "output", "produce result"],
      ["processor", "offsets", "send offsets"],
      ["txn", "output", "commit marker"],
      ["txn", "offsets", "atomic commit"],
    ],
    callouts: [
      "EOS cobre operações Kafka; efeitos externos ainda exigem estratégia própria.",
      "read_committed esconde registros de transações abortadas.",
      "transactional.id habilita fencing contra instâncias antigas.",
    ],
  },
  "kafka-dlq-idempotency": {
    headline: "Retry e DLQ separam falha temporária de mensagem irrecuperável",
    detail:
      "O fluxo classifica erro, aplica retry com backoff, envia poison message para DLQ e usa idempotency key para replay sem duplicar cobrança.",
    nodes: [
      ["main", "payments.in\nmain topic", "topic", 10, 42],
      ["worker", "Payment worker\nidempotent", "consumer", 34, 42],
      ["retry", "retry.5m\nbackoff", "topic", 58, 22],
      ["dlq", "payments.dlq\nquarantine", "topic", 58, 62],
      ["ledger", "Ledger/API\nidempotency key", "external", 84, 42],
    ],
    flows: [
      ["main", "worker", "consume"],
      ["worker", "ledger", "effect once"],
      ["worker", "retry", "transient error"],
      ["retry", "worker", "delayed replay"],
      ["worker", "dlq", "poison message"],
    ],
    callouts: [
      "DLQ não é descarte; precisa metadata, owner e processo de replay.",
      "Retry infinito bloqueia partitions e esconde incidentes.",
      "Idempotência deve usar chave de negócio estável, não offset.",
    ],
  },
  "kafka-outbox-cdc": {
    headline: "Outbox elimina dual write entre banco e Kafka",
    detail:
      "Pedido e outbox são gravados na mesma transação local; um relay/CDC lê a tabela de outbox e publica no Kafka com deduplicação.",
    nodes: [
      ["service", "Order service\ncommand", "producer", 10, 42],
      ["db", "DB transaction\norder + outbox", "storage", 34, 42],
      ["cdc", "CDC/relay\nreads outbox", "control", 58, 42],
      ["kafka", "Kafka topic\nOrderCreated", "topic", 84, 42],
      ["dedupe", "event_id\nidempotency", "consumer", 58, 72],
    ],
    flows: [
      ["service", "db", "single commit"],
      ["db", "cdc", "change stream"],
      ["cdc", "kafka", "publish event"],
      ["cdc", "dedupe", "event_id"],
      ["dedupe", "kafka", "safe retry"],
    ],
    callouts: [
      "Dual write falha quando DB commit e publish não são atômicos.",
      "Outbox transfere complexidade para relay, limpeza e dedupe.",
      "CDC preserva ordem por log do banco, mas precisa particionamento coerente.",
    ],
  },
  "kafka-stream-processing": {
    headline: "Stateful processing usa state store e changelog topic",
    detail:
      "O vídeo mostra KStream/KTable, join, store local, changelog para restore e saída agregada em tempo quase real.",
    nodes: [
      ["orders", "orders stream\nKStream", "topic", 10, 30],
      ["payments", "payments table\nKTable", "topic", 10, 60],
      ["app", "Streams app\njoin/aggregate", "consumer", 38, 44],
      ["store", "State store\nRocksDB local", "storage", 62, 26],
      ["changelog", "Changelog topic\nrestore", "topic", 62, 62],
      ["output", "metrics topic\nby customer", "topic", 86, 44],
    ],
    flows: [
      ["orders", "app", "stream records"],
      ["payments", "app", "table updates"],
      ["app", "store", "local state"],
      ["store", "changelog", "replicate state"],
      ["changelog", "store", "restore after crash"],
      ["app", "output", "emit aggregate"],
    ],
    callouts: [
      "State store local precisa changelog para recuperação.",
      "Join correto depende de key, janela e semântica de tempo.",
      "Repartition topics aparecem quando a key não está alinhada.",
    ],
  },
  "kafka-performance-tuning": {
    headline: "Throughput vem de batching, compressão e paralelismo bem medidos",
    detail:
      "A cena acompanha producer batching/linger, compressão, broker I/O e fetch maior no consumer para mostrar trade-off de latência p95.",
    nodes: [
      ["producer", "Producer\nlinger + batch", "producer", 10, 42],
      ["compress", "Compression\nlz4/zstd", "control", 32, 42],
      ["broker", "Broker\nnetwork + disk", "broker", 56, 42],
      ["partitions", "Partitions\nparallel lanes", "topic", 76, 24],
      ["consumer", "Consumer\nfetch.min/max", "consumer", 88, 58],
      ["metrics", "Metrics\np95 + MB/s", "storage", 56, 72],
    ],
    flows: [
      ["producer", "compress", "batch bytes"],
      ["compress", "broker", "fewer requests"],
      ["broker", "partitions", "append parallel"],
      ["partitions", "consumer", "larger fetch"],
      ["broker", "metrics", "measure"],
      ["consumer", "metrics", "latency/lag"],
    ],
    callouts: [
      "Linger aumenta chance de batch maior, mas adiciona espera.",
      "Compressão poupa rede/disco e gasta CPU.",
      "Tuning sem baseline vira palpite; compare throughput, lag e p95.",
    ],
  },
  "kafka-security-quotas": {
    headline: "Segurança combina identidade, autorização e limites de uso",
    detail:
      "O desenho separa TLS/SASL, principal autenticado, ACL por recurso e quotas para evitar que um tenant prejudique o cluster inteiro.",
    nodes: [
      ["client", "Client app\nprincipal", "producer", 10, 42],
      ["tls", "TLS/SASL\nauthn", "control", 32, 42],
      ["acl", "ACL engine\nauthz", "control", 54, 26],
      ["quota", "Quota\nthrottle", "control", 54, 62],
      ["broker", "Broker\ntenant boundary", "broker", 78, 42],
      ["audit", "Audit logs\naccess trail", "storage", 78, 72],
    ],
    flows: [
      ["client", "tls", "authenticate"],
      ["tls", "acl", "principal"],
      ["acl", "broker", "allow/deny"],
      ["quota", "broker", "rate limit"],
      ["broker", "audit", "record access"],
      ["tls", "quota", "client id"],
    ],
    callouts: [
      "TLS protege canal; SASL identifica cliente; ACL autoriza ação.",
      "Quotas protegem o cluster de produtores/consumidores barulhentos.",
      "Least privilege precisa ser testado como parte do lab.",
    ],
  },
  "kafka-observability-incidents": {
    headline: "Incidente Kafka é leitura coordenada de lag, ISR, disco e capacidade",
    detail:
      "A animação conecta sintomas, métricas e runbook para diagnosticar se o problema é consumer lento, broker degradado, partição quente ou retenção/capacidade.",
    nodes: [
      ["alerts", "Alerts\nlag/URP/disk", "control", 10, 42],
      ["dashboard", "Dashboard\nSLO view", "storage", 34, 42],
      ["consumer", "Consumer group\nlag by partition", "consumer", 58, 22],
      ["cluster", "Cluster\nISR + leaders", "broker", 58, 62],
      ["runbook", "Runbook\nmitigate", "external", 84, 42],
      ["dr", "DR plan\nrestore/RPO", "storage", 84, 72],
    ],
    flows: [
      ["alerts", "dashboard", "triage"],
      ["dashboard", "consumer", "lag drilldown"],
      ["dashboard", "cluster", "broker health"],
      ["consumer", "runbook", "scale/replay"],
      ["cluster", "runbook", "move leaders/capacity"],
      ["runbook", "dr", "post-incident"],
    ],
    callouts: [
      "Consumer lag isolado não prova falha do broker.",
      "Under-replicated partitions indicam risco de durabilidade/disponibilidade.",
      "Runbook deve ligar métrica a ação, dono e critério de rollback.",
    ],
  },
};

for (const challenge of videoChallenges) {
  if (kafkaVisuals[challenge.id]) {
    challenge.visual = kafkaVisuals[challenge.id];
  }
}

module.exports = { videoChallenges };
